name: FoxPlugin
version: '1.0-SNAPSHOT'
main: de.foxy.main.Main
api-version: 1.18
authors: [ foxy ]
commands:
  heal:
  fly:
  gamemode:
    aliases: gm
  tpo:
  tphere:
  tp:
  weather:
    aliases: w
  time:
    aliases: t
  kill: